### ISSUE TITLE
call loss function problem

### ISSUE THREAD

**Issue by TanYuzhen** [s4nyam/gradcam-yolo#1]
However,when I run the code,it always produces the error :
      the x_adv.grad is None

       But the correct thing should be not None.Can you help me to solve the problem?
      
![thumbnail_image](https://github.com/s4nyam/gradcam-yolo/assets/101782729/fc1380ce-443f-4ebb-8a6a-86a6cf4c348a)

       And,I read your code,finding that you didn't use the function forward in the class pgd ,I'm not sure whether I'm wrong
![thumbnail_image2](https://github.com/s4nyam/gradcam-yolo/assets/101782729/ccb589a9-fa49-4558-8c79-d5fa96816718)

      Thanks a lot!

**Comment by s4nyam** [comment]
Hi @TanYuzhen I have tried to resolve the problem in this notebook.
Can you please use this google colab for reference.
https://colab.research.google.com/drive/1X6Y1CGYlklQ3lhdZblTfSYlLqNNVY4Gj?usp=sharing

**Comment by s4nyam** [comment]
The running google colab notebook was provided.
