### ISSUE TITLE
Code explaination needed

### ISSUE THREAD

**Issue by lesonglam** [s4nyam/gradcam-yolo#2]
I have 2 questions related to this file.
https://github.com/s4nyam/gradcam-yolo/blob/main/experiment4_attacks/BIM(Iterative_FGSM).ipynb

1. In this file from your github repo, you create an instance of PGD attack, But I don't see you using it anywhere.
model_pgd = PGD(model=model,config='random_init')

2. In addition, in this code block, why did you create Text on the image as fixed ("Stop sign"). I thought this label should be from the predicted value.
<img width="524" alt="image" src="https://github.com/user-attachments/assets/45e21368-bb80-4fc9-aec4-6d867a173b72">

**Comment by s4nyam** [comment]
Hi, sorry for late reply, please ignore the leakage and try to predict directly, at some point, as I recall, it might be used while experimenting to see label dispersion by the attacks. If you have time (or want to improve upon it), I can make you collaborator for this repo.

**Comment by lesonglam** [comment]
The only way to improve it iff it works. I still don't know why you put hard code to show the label "Stop Sign".
