### ISSUE TITLE
Google Drive links used in .ipynb files are not working

### ISSUE THREAD

**Issue by GiosueSglavo** [s4nyam/gradcam-yolo#3]
Can you provide valid links for the files that are downloaded into .ipynb spreadsheets?
Thanks in advance

**Comment by s4nyam** [comment]
Please download the same files from here
https://universe.roboflow.com/ds/YSARnwUS4k?key=AFwgIs37Hg

**Comment by GiosueSglavo** [comment]
Thank you so much!
